/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AVoidReturnType extends PReturnType
{

    public AVoidReturnType()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AVoidReturnType();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVoidReturnType(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
