/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TArgsSymbol extends Token
{
    public TArgsSymbol()
    {
        super.setText("args");
    }

    public TArgsSymbol(int line, int pos)
    {
        super.setText("args");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TArgsSymbol(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTArgsSymbol(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TArgsSymbol text.");
    }
}
