/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TCmpEqualsSmaller extends Token
{
    public TCmpEqualsSmaller()
    {
        super.setText("<=");
    }

    public TCmpEqualsSmaller(int line, int pos)
    {
        super.setText("<=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCmpEqualsSmaller(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCmpEqualsSmaller(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCmpEqualsSmaller text.");
    }
}
