/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TConsoleSymbol extends Token
{
    public TConsoleSymbol()
    {
        super.setText("Console");
    }

    public TConsoleSymbol(int line, int pos)
    {
        super.setText("Console");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TConsoleSymbol(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTConsoleSymbol(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TConsoleSymbol text.");
    }
}
