/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TUsingSymbol extends Token
{
    public TUsingSymbol()
    {
        super.setText("using");
    }

    public TUsingSymbol(int line, int pos)
    {
        super.setText("using");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TUsingSymbol(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUsingSymbol(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TUsingSymbol text.");
    }
}
