/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TWriteLineSymbol extends Token
{
    public TWriteLineSymbol()
    {
        super.setText("WriteLine");
    }

    public TWriteLineSymbol(int line, int pos)
    {
        super.setText("WriteLine");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TWriteLineSymbol(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTWriteLineSymbol(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TWriteLineSymbol text.");
    }
}
